<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sanyan</groupId>
        <artifactId>sanyan-server-parent</artifactId>
        <version>0.1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>bootstrap</artifactId>
    <name>sanyan-server-bootstrap</name>

    <dependencies>
        <dependency><groupId>com.sanyan</groupId><artifactId>sanyan-business</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency>
    </dependencies>

    <build>
        <finalName>sanyan-server-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions><execution><goals><goal>repackage</goal></goals></execution></executions>
            </plugin>
        </plugins>
    </build>
</project>
